package com.home.mouse.server.processors.model;

public enum Commands {
    EXIT,
    MOVE,
    CLEAN,
    REFRESH,
    SHOW,
    MOUSEPRESS1,
    MOUSERELEASE1,
    CONTAINSINRANGE,
    CONTAINSALL,
    CONTAINSALLINRANGE, LCLICK, MCLICK, RCLICK, DBLCLICK, PRESSKEY, SLEEP, SCREEN2FILE, SCREENRANGE2FILE,
    CONTAINS,
    CONTAINSOLD,
    CONTAINSALLOLD,
    CONTAINSINSCREEN,
    CONTAINSEX,
    CONTAINSINSCREENEX,
    GETCOLOR, PRINT;
}
